version: '3'

services:
  postgres:
    image: postgres:15
    container_name: 24h_postgres
    environment:
      POSTGRES_DB: 24heures_strapi_dev
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - 24h_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: 24h_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@24heures.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - 24h_network

volumes:
  postgres_data:

networks:
  24h_network:
    driver: bridge 